### ISSUE TITLE
UI tweaks

### ISSUE THREAD

**Issue by SidoPillai** [jer2wcs/JeremyBryan_ESRIWeatherApp#2]
Dock the flickable such that the list view doesn't exceed the bounds at the same time it honors scrollability.

![feedback-weather-app](https://user-images.githubusercontent.com/4101783/84804773-1d619880-afb8-11ea-8dec-fe6774149c63.gif)

Weather units is not mentioned, it will be nice to have a switch units feature between celsius and fahrenheit 

Nice to have a current state such as mist, sunny etc with an icon.

Live text in the bottom can be made little nice
<img width="48" alt="Screen Shot 2020-06-16 at 10 05 37 AM" src="https://user-images.githubusercontent.com/4101783/84805374-01122b80-afb9-11ea-8581-c9b826dd8821.png">

Handle failure states, when weather data is not available or device is offline.

The view is not rendered well in iPhone
<img width="521" alt="Screen Shot 2020-06-16 at 10 08 52 AM" src="https://user-images.githubusercontent.com/4101783/84805621-6403c280-afb9-11ea-9b66-a4236101c23a.png">

**Comment by jer2wcs** [comment]
@siddeshpillai: I'm not sure how to target an iPhone device for rendering. I don't see that anywhere in my settings or virtual devices.

**Comment by SidoPillai** [comment]
Make sure the layouts are `anchors.fill: parent`

**Comment by jer2wcs** [comment]
Done (for the most part)

@siddeshpillai said: "Handle failure states, when weather data is not available or device is offline."
I'm not sure what you mean by this part. I believe I do handle failures from the HTTP request. If I get an error back I used cached data. Was there something else you were envisioning?

@siddeshpillai said: "The view is not rendered well in iPhone."
I'm not sure how to address this as I'm not able to target an iPhone that I can see with my current setup. The page's anchor is set to parent.fill, so I'm not sure what else you were referring to.
